source "https://rubygems.org"

gem "dotenv", "~> 3.1"
gem "dry-struct", "~> 1.6"
gem "dry-types", "~> 1.7"
gem "service_actor", "~> 5.0"

group :test do
  gem "minitest", "~> 5.25"
  gem "minitest-reporters", "~> 1.7"
end
