module Spark
  module Actors
    class CreateGithubIssues < Actor
      include Spark::Actors::PipelineInputs

      input :stories
      input :repo_name, type: String
      output :issue_numbers

      def call
        log_actor("Creating GitHub issues from stories")
        update_phase("creating_issues")

        numbers = []

        stories.sort_by(&:number).each do |story|
          body = build_issue_body(story)
          number = Spark::GitHub.create_issue(
            repo_name,
            title: story.title,
            body: body,
            labels: [story.type]
          )
          numbers << number
          log_actor("Created issue ##{number}: #{story.title}")
        end

        self.issue_numbers = numbers
        log_actor("Created #{numbers.length} issues")
      end

      private

      def build_issue_body(story)
        parts = [story.description, ""]

        if story.acceptance_criteria.any?
          parts << "## Acceptance Criteria"
          story.acceptance_criteria.each { |ac| parts << "- [ ] #{ac}" }
          parts << ""
        end

        if story.depends_on.any?
          parts << "## Dependencies"
          story.depends_on.each { |dep| parts << "- Depends on story ##{dep}" }
          parts << ""
        end

        parts << "---"
        parts << "_Generated by Spark_"
        parts.join("\n")
      end
    end
  end
end
